workflows:
  android-debug:
    name: Android Debug APK
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "com.urizon.scannerapp"
      node: 18
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web assets
        script: |
          npm run build || true
      - name: Add Android platform
        script: |
          npx cap add android || true
      - name: Sync Capacitor
        script: |
          npx cap sync android
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
